@0xb7e4c1a9f3d28e56;

# CriomOS PKI Enrollment Protocol
#
# Transport: RIST Main Profile (DTLS-PSK, reliable UDP)
# Discovery: mDNS/DNS-SD (_criom-ca._tcp.local)
# Auth:      Join token = DTLS pre-shared key
#
# Flow:
#   1. Node boots, generates complex (Ed25519 keypair)
#   2. Node discovers CA via mDNS browse
#   3. Node connects via RIST Main Profile using join token as PSK
#   4. Node sends EnrollmentRequest
#   5. CA validates, signs, returns EnrollmentResponse
#   6. Node writes certs, restarts wifi-eap
#
# The join token serves double duty:
#   - DTLS-PSK for transport authentication (mutual)
#   - Proof of authorization (admin generated it for this node)
#
# After enrollment, the token is burned. All future auth
# is certificate-based (EAP-TLS, SSH, etc).

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("criom::enrollment");


# ── Discovery ──

struct CaAnnouncement {
  # Published as mDNS TXT record fields on _criom-ca._tcp.local
  clusterName  @0 :Text;           # e.g. "maisiliym"
  caFingerprint @1 :Data;          # SHA-256 of CA certificate DER (32 bytes)
  ristPort     @2 :UInt16;         # RIST listener port
  protocol     @3 :UInt16 = 1;     # Protocol version
}


# ── Enrollment Request (Node → CA) ──

struct EnrollmentRequest {
  # The node presents its self-generated identity for signing.
  # The node never sends private key material.

  nodeName     @0 :Text;           # Hostname (e.g. "probus")
  clusterName  @1 :Text;           # Cluster it claims to belong to
  sshPubkey    @2 :Text;           # OpenSSH Ed25519 pubkey from complex
                                    # "ssh-ed25519 AAAA... complex"
  cn           @3 :Text;           # Requested certificate CN (e.g. "probus@aedifico")

  # Proof of possession: node signs a challenge with its complex key
  # to prove it holds the private key corresponding to sshPubkey.
  # The challenge is the SHA-256 of (sshPubkey || nonce).
  nonce        @4 :Data;           # Random 32 bytes generated by node
  proof        @5 :Data;           # Ed25519 signature over SHA-256(sshPubkey || nonce)
}


# ── Enrollment Response (CA → Node) ──

struct EnrollmentResponse {
  union {
    success :group {
      nodeCert   @0 :Data;         # PEM-encoded X.509 client certificate
      caCert     @1 :Data;         # PEM-encoded CA certificate
      expiresAt  @2 :Int64;        # Unix timestamp of cert expiry
    }

    denied :group {
      reason     @3 :Text;         # Human-readable rejection reason
    }

    error :group {
      code       @4 :UInt16;       # Machine-readable error code
      message    @5 :Text;         # Human-readable error message
    }
  }
}


# ── Renewal Request (Node → CA, over existing authenticated channel) ──

struct RenewalRequest {
  # Sent over an already-authenticated channel (e.g. Yggdrasil + TLS)
  # after initial enrollment, when the certificate approaches expiry.

  nodeName     @0 :Text;
  currentCert  @1 :Data;           # PEM of the current (still-valid) certificate
  sshPubkey    @2 :Text;           # Current complex pubkey (may have changed if key rotated)
  cn           @3 :Text;
  proof        @4 :Data;           # Ed25519 signature proving possession of current key
}

struct RenewalResponse {
  union {
    success :group {
      nodeCert   @0 :Data;         # New PEM certificate
      caCert     @1 :Data;         # CA cert (may have rotated)
      expiresAt  @2 :Int64;
    }

    denied :group {
      reason     @3 :Text;
    }
  }
}


# ── Server Certificate Request (Router → CA) ──

struct ServerCertRequest {
  # Router requests a P-256 server certificate for hostapd EAP-TLS.
  # The router generates its own P-256 keypair and sends the public key.

  nodeName     @0 :Text;
  cn           @1 :Text;           # e.g. "asklepios.criome"
  publicKey    @2 :Data;           # P-256 public key (uncompressed SEC1, 65 bytes)
  proof        @3 :Data;           # Signature from the router's complex key
}

struct ServerCertResponse {
  union {
    success :group {
      serverCert @0 :Data;         # PEM server certificate (P-256 subject key)
      caCert     @1 :Data;         # PEM CA certificate
      expiresAt  @2 :Int64;
    }

    denied :group {
      reason     @3 :Text;
    }
  }
}


# ── Error Codes ──

const unknownCluster    :UInt16 = 1;
const unknownNode       :UInt16 = 2;
const invalidToken      :UInt16 = 3;
const invalidProof      :UInt16 = 4;
const alreadyEnrolled   :UInt16 = 5;
const caUnavailable     :UInt16 = 6;
const rateLimited       :UInt16 = 7;
